apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-api
  namespace: cafe-boreal
  labels:
    app: catalog-api
    app.kubernetes.io/part-of: cafe-boreal
spec:
  replicas: 1

  selector:
    matchLabels:
      app: catalog-api

  template:
    metadata:
      labels:
        app: catalog-api
        app.kubernetes.io/part-of: cafe-boreal

    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 999
        seccompProfile:
          type: RuntimeDefault

      containers:
        - name: catalog-api
          image: cafe-boreal/catalog-api:v1
          imagePullPolicy: Never

          ports:
            - name: http
              containerPort: 8000
              protocol: TCP

          env:
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"

          envFrom:
            - configMapRef:
                name: postgres-config
            - secretRef:
                name: postgres-secret

          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi

          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
