apiVersion: v1
kind: Service
metadata:
  name: orders-api
  namespace: cafe-boreal
  labels:
    app: orders-api
    app.kubernetes.io/part-of: cafe-boreal

spec:
  type: ClusterIP

  selector:
    app: orders-api

  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
