{
 "title": "Cafe Boreal - Infraestructura y Servicios",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CPU por contenedor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (container) (rate(container_cpu_usage_seconds_total{container!=\"\"}[5m]))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memoria por contenedor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (container) (container_memory_working_set_bytes{container!=\"\"})",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Errores HTTP 5xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"cafe-boreal\"} |~ \" 5[0-9][0-9] \" [5m]))"
    }
   ]
  },
  {
   "title": "Logs Cafe Boreal",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{namespace=\"cafe-boreal\"}"
    }
   ]
  }
 ]
}